.TH "face.hpp" 3 "Thu Oct 22 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
face.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'point\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFace\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
