.TH "Face" 3 "Thu Oct 22 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Face \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <face\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFace\fP ()"
.br
.RI "\fIConstructeur & Destructeur\&. \fP"
.ti -1c
.RI "\fB~Face\fP ()"
.br
.ti -1c
.RI "long unsigned \fBgetS_one\fP () const "
.br
.RI "\fIGetter & Setter\&. \fP"
.ti -1c
.RI "long unsigned \fBgetS_two\fP () const "
.br
.ti -1c
.RI "long unsigned \fBgetS_three\fP () const "
.br
.ti -1c
.RI "double \fBgetSeg_one\fP () const "
.br
.RI "\fIGetters segments\&. \fP"
.ti -1c
.RI "double \fBgetSeg_two\fP () const "
.br
.ti -1c
.RI "double \fBgetSeg_three\fP () const "
.br
.ti -1c
.RI "double \fBgetPerimeter\fP () const "
.br
.RI "\fIGetters perimetre\&. \fP"
.ti -1c
.RI "double \fBgetArea\fP () const "
.br
.RI "\fIGetters aire\&. \fP"
.ti -1c
.RI "void \fBsetS_one\fP (const long unsigned &)"
.br
.RI "\fISetteur sommets\&. \fP"
.ti -1c
.RI "void \fBsetS_two\fP (const long unsigned &)"
.br
.ti -1c
.RI "void \fBsetS_three\fP (const long unsigned &)"
.br
.ti -1c
.RI "void \fBsetSeg_one\fP (const double &)"
.br
.RI "\fISetteur segments\&. \fP"
.ti -1c
.RI "void \fBsetSeg_two\fP (const double &)"
.br
.ti -1c
.RI "void \fBsetSeg_three\fP (const double &)"
.br
.ti -1c
.RI "void \fBsetPerimeter\fP (const double &)"
.br
.RI "\fISetteur perimetre\&. \fP"
.ti -1c
.RI "void \fBsetArea\fP (const double &)"
.br
.RI "\fISetteur aire\&. \fP"
.ti -1c
.RI "double \fBcalc_area\fP (double, double, double)"
.br
.RI "\fICalcul de l'aire du triangle en fonction des calculs de distance entre les points (classe \fBPoint\fP) \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Face::Face ()"

.PP
Constructeur & Destructeur\&. Très certainement include math pour sqrt Créer trois autres membres qui sont les longueurs AB, BC et CA ? 
.SS "Face::~Face ()"

.SH "Member Function Documentation"
.PP 
.SS "double Face::calc_area (doubleAB, doubleBC, doubleCA)"

.PP
Calcul de l'aire du triangle en fonction des calculs de distance entre les points (classe \fBPoint\fP) Utilisation de la formule d'Héron : AB étant le segment composé du point A et du point B 
.SS "double Face::getArea () const"

.PP
Getters aire\&. 
.SS "double Face::getPerimeter () const"

.PP
Getters perimetre\&. 
.SS "long unsigned Face::getS_one () const"

.PP
Getter & Setter\&. Getters sommets\&. 
.SS "long unsigned Face::getS_three () const"

.SS "long unsigned Face::getS_two () const"

.SS "double Face::getSeg_one () const"

.PP
Getters segments\&. 
.SS "double Face::getSeg_three () const"

.SS "double Face::getSeg_two () const"

.SS "void Face::setArea (const double &_area)"

.PP
Setteur aire\&. 
.SS "void Face::setPerimeter (const double &_perimeter)"

.PP
Setteur perimetre\&. 
.SS "void Face::setS_one (const long unsigned &_one)"

.PP
Setteur sommets\&. 
.SS "void Face::setS_three (const long unsigned &_three)"

.SS "void Face::setS_two (const long unsigned &_two)"

.SS "void Face::setSeg_one (const double &s_one)"

.PP
Setteur segments\&. 
.SS "void Face::setSeg_three (const double &s_three)"

.SS "void Face::setSeg_two (const double &s_two)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
