.TH "Point" 3 "Thu Oct 22 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <point\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint\fP ()"
.br
.RI "\fIConstructeur & Desctructeur\&. \fP"
.ti -1c
.RI "\fB~Point\fP ()"
.br
.ti -1c
.RI "double \fBgetP_one\fP () const "
.br
.RI "\fIGetters & Setters\&. \fP"
.ti -1c
.RI "double \fBgetP_two\fP () const "
.br
.ti -1c
.RI "double \fBgetP_three\fP () const "
.br
.ti -1c
.RI "void \fBsetP_one\fP (const double &)"
.br
.ti -1c
.RI "void \fBsetP_two\fP (const double &)"
.br
.ti -1c
.RI "void \fBsetP_three\fP (const double &)"
.br
.ti -1c
.RI "double \fBcalc_length\fP (double, double)"
.br
.RI "\fICalcul longueur entre les points\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Point::Point ()"

.PP
Constructeur & Desctructeur\&. Constructeur & Destructeur\&. 
.SS "Point::~Point ()"

.SH "Member Function Documentation"
.PP 
.SS "double Point::calc_length (doubleA, doubleB)"

.PP
Calcul longueur entre les points\&. Methodes Calcul d'une longueur d'un segment d'une face suivant les coordonnées de deux sommets 
.SS "double Point::getP_one () const"

.PP
Getters & Setters\&. Getter & Setter\&. 
.SS "double Point::getP_three () const"

.SS "double Point::getP_two () const"

.SS "void Point::setP_one (const double &_one)"

.SS "void Point::setP_three (const double &_three)"

.SS "void Point::setP_two (const double &_two)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
