#!/bin/bash
chmod u+x grepmod

echo "-- Compilation --"
g++ -Wall -c main.cpp face.cpp point.cpp mesh.cpp

file=`ls|grep main.o`

if [ "$file" = "main.o" ];then
g++ -Wall -o main main.o face.o point.o mesh.o

echo "-- Execution --"

echo "-----------------------------------------------------"

memfreestart=`cat /proc/meminfo | grep MemFree`
echo "start : "$memfreestart > infomem.txt

time ./main

echo `cat infomem.txt`
else
	echo "-- Error: Failed compilation --"
	rm *.o
	exit
fi

echo "------------------------------------------------------"
echo "Voulez-vous afficher la documentation en ligne ? (y/n)"
read y

if [ $y = "y" ]; then
firefox ../Doxygen/html/annotated.html

fi

echo "		@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "		@         Projet Systeme - M3101 :       @"
echo "		@       Programmation Séquentielle       @"
echo "		@ Calcul de surface d'un Objet 3D Maillé @"
echo "		@   Guillaume BOEHM & Thibault HECKEL    @"
echo "		@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

rm *.o

exit
